name: assistantwithai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
  - assets/undraw_fitness_tracker.png
  - assets/undraw_personal_training.png
  - assets/undraw_Working_out_re_nhkg.png
